### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by fycarman** [ItalianDevs4PM/Yuriko-MP#3]
To-Do list for Yuriko-MP v1.6.1 dev-1

Blocks and Items:
To Implement:
- [ ] Potions
- [ ] Enchanted Books
- [ ] Redstone related blocks
- [ ] Rails
- [ ] Minecarts
- [ ] Fishing Rod
- [ ] Trapped Chests
- [ ] Note Blocks
- [ ] Mob eggs
- [ ] Other new blocks

To fix:
- [ ] Flower Pot
- [ ] TNT's lateral textures are rotated weirdly (when dropped)
- [ ] Doors drop tile.OakDoor.name when breaked (I tried with explosion)
- [ ] Redstone lamp in inventory
- [ ] There are two blank boxes at the bottom of the creative inventory (building blocks)
- [ ] Other fixes

Gameplay:
To implement:
- [ ] Experience
- [ ] Enchanting
- [ ] Brewing
- [ ] Nether
- [ ] Redstone Mechanics
- [ ] Mobs and Mob AI
- [ ] Weather

To fix:
- [ ] Crafting recipes
- [ ] Water does not cancel the fall damage
- [ ] Redstone does not restore previous status of things when power is off
- [ ] Redstone does not power trapdoors, iron trapdoors and fence gates
- [ ] Normal blocks can't stop Redstone impulse
- [ ] Redstone does not power lateral bottom blocks (TNT Cannon)
- [ ] Redstone torches can't turn off by a redstone impulse
- [ ] Redstone torches can't turn on redstone wire while them are placed under or in side of the block in the bottom of redstone wire
- [ ] Iron doors can be opened like normal doors
- [ ] Cannot place more than 2 snow layers in top to a snow block
- [ ] Sometimes player gets stuck when moving on slabs or other "half blocks"
- [ ] Experience and hunger don't get saved
- [ ] When a player deaths he cannot respawn and there is a critical error in the console
- [ ] Other fixes

Server related things:
Server related:
- [ ] Implement Super OP
- [ ] Implement player data in a SQL Database
- [ ] Implement Client ID checking (with API for plugins)
- [ ] Implement /console command (run commands as console)
- [ ] Implement /ping command
- [ ] Implement /setblock 
- [ ] Implement advanced commands' aliases
- [ ] Implement /r command (re-do precedent command)
- [ ] Implement better anti-cheat
- [ ] Implement proxy software (like FastTransfer but not FastTransfer) (with API for plugins)
- [ ] Implement /tpa command
- [ ] Fix /xp command's translations
- [ ] Fix /info when no player is defined
- [ ] Fix experience API: Can't obtain Experience Levels (getExpLevels() function)
- [ ] PHP7 support (only after all things are implemented/fixed)

Source files related:
- [ ] Make Yuriko-MP Ascii Art on every single file
- [ ] Make Yuriko-MP Logo
- [ ] Clean up all the code and use right variables' name

**Comment by fycarman** [comment]
Just ported all To-Do list @AryToNeX @luca28pet @xionbig @XEmAX32 @Flavius12
